[package]
name = "RustyChef"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
sqlite = "0.26.0"
reqwest = { version = "0.11", features = ["blocking","json"] }
json = "0.12.4"
